#!/bin/sh

only_osx() {
  [ $(uname -s) != "Darwin" ] && exit 0
}

only_osx

BREW_PACKAGES=(
  aria2
  asciinema
  ctags
  curl
  direnv
  fasd
  git
  git-extras
  git-duet/tap/git-duet
  go
  htop
  jq
  lua
  mercurial
  mongodb
  neovim/neovim/neovim
  openssl
  pcre
  pstree
  reattach-to-user-namespace
  redis
  the_silver_searcher
  tig
  tmate
  tmux
  tree
  watch
  wget
  )

CASK_PACKAGES=(
  alfred
  colloquy
  dropbox
  google-chrome
  iterm2
  screenhero
  shiftit
  skype
  slack
  spotify
  sublime
  vagrant
  virtualbox
)

install_brew() {
  if test  ! $(which brew)
  then
    echo "Downloading homebrew..."
    $(which ruby) -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /tmp/homebrew.log
  fi
}

update_brew_packages() {
  brew update
  brew upgrade

  for pkg in ${BREW_PACKAGES[@]}; do
  brew install $pkg
  done

  brew cleanup -s
}

update_cask_packages() {
  brew cask update

  for pkg in ${CASK_PACKAGES[@]}; do
    brew cask install $pkg
  done

  brew cask cleanup
}

only_osx
install_brew
update_brew_packages
update_cask_packages
