#!/bin/bash

HOURS="$1"

if [ -z "$HOURS" ]; then
  HOURS="12"
fi

/usr/bin/ssh-add -D

trap "rm -f ssh-key && rm -f passwd" EXIT

op item get ssh-key --fields "private key" --reveal --format json | jq -r .ssh_formats.openssh.value > ssh-key
op item get ssh-key --fields "password" --reveal --format json | jq -r .value > passwd

chmod 600 ssh-key

DISPLAY=1 SSH_ASKPASS=ssh-pass ssh-add -t "$HOURS"H ssh-key <<< `cat passwd`
