#!/bin/bash

set -e

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

update_symlinks() {
  for file in $(find `pwd` -name "*.symlink")
  do
    destination="$HOME/.`basename \"${file%.*}\"`"

    # Create a backup if a file exists
    if [[  -f $destination ]] || [[ -L $destination ]]
    then
      mv $destination "${destination}.backup"
    fi

    # Move file
    ln -s  $1 $2
    success "Liked $1 to $2"
  done
}

install_scripts() {
  for file in $(find `pwd` -maxdepth 3 -name "install")
  do
    sh -c $file
  done
}

update_functions() {
  for file in $(ls `pwd`/functions)
  do
    ln -s /usr/local/bin $file
  done
}

update_symlinks
install_scripts
update_functions
