#!/usr/bin/env bash

set -euo pipefail

log() {
  echo
  echo "----------------------------------------------------------------------"
  echo "$1"
  echo "----------------------------------------------------------------------"
  echo
}

install_ansible() {
  log "Installing/upgrading Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install ansible
}

linux_install_ansible() {
  log "Installing/upgrading Ansible"
  sudo apt update
  sudo apt install software-properties-common --yes
  sudo add-apt-repository --yes --update ppa:ansible/ansible
  sudo apt install ansible --yes
}

log "Installing/Updating home..."

if ! which ansible-playbook > /dev/null 2>&1 ; then
  echo "ansible-playbook not found on \$PATH, installing"

  if [ "$(uname -s)" == "Darwin" ]; then
    install_ansible
  elif [ "$(uname -s)" == "Linux" ]; then
    linux_install_ansible
  fi
fi

(
  cd "$(dirname "$0")"

  cmd="ansible-playbook --inventory localhost, --connection local playbook.yml"
  $cmd
)
