#!/bin/bash

main() {
  only_ubuntu

  install_packages
  install_neovim
}

install_packages() {
  sudo apt-get install software-properties-common
  sudo apt-get update -y

  for repo in ${REPOSITORIES[@]}; do
    sudo add-apt-repository $repo
  done

  sudo apt-get udpate
  for pkg in ${PACKAGES[@]}; do
    sudo apt-get install -y $pkg
  done

  install_go
  install_fzf
}

install_go() {
  which go && return
  wget -O go.tgz https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
  sudo tar -xzvf go.tgz -C /usr/local
  rm go.tgz
}

install_fzf() {
  which fzf && return
  wget -O fzf.tgz https://github.com/junegunn/fzf/archive/0.17.3.tar.gz
  tar -xzvf fzf.tgz
  sudo mv fzf-0.17.3 /usr/local/bin/fzf
  rm fzf.tgz
}

install_neovim() {
  pip3 install neovim
}

REPOSITORIES=(
  "ppa:aacebedo/fasd"
  "ppa:nviennot/tmate"
  "ppa:neovim-ppa/stable"
)

PACKAGES=(
  "ack-grep"
  "coreutils"
  "direnv"
  "docker-compose"
  "fasd"
  "gcc"
  "git"
  "git-extras"
  "jq" "make"
  "neovim"
  "npm"
  "python3-dev"
  "python3-pip"
  "silversearcher-ag"
  "tig"
  "tmate"
  "tmux"
  "tree"
  "unzip"
  "vim-nox"
  "watch"
)

only_ubuntu() {
  [[ $(uname -s) != "Linux" ]] && exit 0
}

main
