source ~/.work.zshrc
source ~/.aliases

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="pairing"


# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR=nvim

export PATH=/usr/local/share/chruby:$HOME/bin:/usr/local/bin:$PATH
export GOPATH=$HOME/workspace
export PATH=$GOPATH/bin:$PATH

export GIT_DUET_GLOBAL=true
export GIT_DUET_ROTATE_AUTHOR=1
export GIT_DUET_CO_AUTHORED_BY=1


export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_EMOJI=1

export GPG_TTY=$(tty)

source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

eval "$(direnv hook zsh)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
if [ -e /Users/aleal/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/aleal/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
[[ -x /usr/local/bin/brew ]] && eval $(/usr/local/bin/brew shellenv)

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)

