source ~/.work.zshrc
source ~/.aliases

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="dracula"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR=nvim

export PATH=/opt/homebrew/bin/:$HOME/bin:/usr/local/bin:/opt/homebrew/opt/openjdk/bin:$PATH
export GOPATH=$HOME/workspace
export PATH=$GOPATH/bin:$PATH

export GIT_DUET_GLOBAL=true
export GIT_DUET_ROTATE_AUTHOR=1
export GIT_DUET_CO_AUTHORED_BY=1


export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_EMOJI=1

export GPG_TTY=$(tty)
export TERM="xterm"

eval "$(direnv hook zsh)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -e /Users/aleal/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/aleal/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. /opt/homebrew/opt/asdf/libexec/asdf.sh
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
export TESTCONTAINERS_HOST_OVERRIDE=$(colima ls -j | jq -r '.address')
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
export TESTCONTAINERS_RYUK_DISABLED=true
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"


prompt_git_name() {
  if $(git config --get duet.env.git-author-name >/dev/null 2>&1); then
    prompt_git_duet_name
  fi
}

prompt_git_duet_name() {
  local author_name=`git config --get duet.env.git-author-initials`
  local committer_name=`git config --get duet.env.git-committer-initials`
  local prompt=""

  [[ $author_name ]] && prompt="$author_name"
  [[ $committer_name ]] && prompt="$prompt+$committer_name"

  echo $prompt
}

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"

PROMPT="$(prompt_git_name) %(?:%{$fg_bold[green]%}➜:%{$fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

# Created by `pipx` on 2024-09-20 18:53:20
export PATH="$PATH:/Users/alberto.leal/.local/bin"
