#!/bin/bash

install_tpm() {
  mkdir -p $HOME/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm $1
}

update_tpm() {
  cd $1
  git reset --hard HEAD
  git pull -r
}

TPM_DIR=$HOME/.tmux/plugins/tpm
if [ ! -d $TPM_DIR ]; then
  install_tpm $TPM_DIR
else
  update_tpm $TPM_DIR
fi

