#!/bin/bash

install_tpm() {
  mkdir -p $HOME/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm $1
}

install_bash_it() {
  git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
  ~/.bash_it/install.sh
}

update_tpm() {
  cd $1
  git reset --hard HEAD
  git pull -r
}

TPM_DIR=$HOME/.tmux/plugins/tpm
if [ ! -d $TPM_DIR ]; then
  install_tpm $TPM_DIR
  install_bash_it
else
  update_tpm $TPM_DIR
fi

